# Generated by Django 5.2.15 on 2026-06-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('github_url', models.URLField(verbose_name='Ссылка на GitHub')),
            ],
            options={
                'verbose_name': 'Профиль резюме',
                'verbose_name_plural': 'Профили резюме',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО Студента')),
                ('folder_name', models.CharField(max_length=100, verbose_name='Имя папки в датасете (латиница)')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория (например, Бэкенд, ИИ, Инструменты)')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_app.resumeprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время сканирования')),
                ('confidence', models.FloatField(verbose_name='Точность совпадения (в %)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='resume_app.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Лог распознавания',
                'verbose_name_plural': 'Логи распознавания',
                'ordering': ['-timestamp'],
            },
        ),
    ]
